### ISSUE TITLE
unable to build projects

### ISSUE THREAD

**Issue by burakulutoprak** [sensiasoft/lib-sensorml#2]
Hi, 
After git clone i am trying to build maven projects but i get following error. 
ERROR] /home/bulutoprak/Jar/sensorml/lib-sensorml-master/sensorml-core/src/main/java/net/opengis/sensorml/v20/AbstractPhysicalProcess.java:[22,27] package net.opengis.swe.v20 does not exist

**Comment by burakulutoprak** [comment]
I noticed i need to first install swe-common-all

**Comment by paulvitic** [comment]
Su anda proje biraz dagaldi. issue 12 uzerinde calisiyorum. vast library
sini cikariyorum. Ama issue 12 yi master a merge etmedim. Tam bitene kadar
biray problem olabilir
